name: Editor tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - online_editor/**

jobs:
  editor:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        node-version: [26]

    steps:
    - uses: actions/checkout@v2
    - name: Editor - Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # using workspace as yarn workspaces only geenrate lock files in the root
    - run: |
        yarn install
        yarn workspace @clyde-lang/parser build
        yarn workspace @clyde-lang/interpreter build
        yarn workspace clyde-online-editor lint
        yarn workspace clyde-online-editor fmt:check
