name: Publish Demo Page

on:
  push:
    branches: [ master ]
    paths:
      - editor/**
      - interpreter/**
      - parser/**

env:
  CI: true

defaults:
  run:
    working-directory: ./editor

jobs:
  publish-gh-pages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install and Build
      # using workspace as yarn workspaces only geenrate lock files in the root
      run: |
        yarn install
        yarn workspace @clyde-lang/parser build
        yarn workspace @clyde-lang/interpreter build
        yarn workspace clyde-editor build

    - name: Deploy  🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./editor/build

